fix error install pipenv lint file BE-CI.yaml

diff --git a/.github/workflows/BE-CI.yaml b/.github/workflows/BE-CI.yaml
--- a/.github/workflows/BE-CI.yaml
+++ b/.github/workflows/BE-CI.yaml
@@ -18,12 +18,12 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Setup Python
+      - name: Setup install Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.10'
 
-      - name: Cache pipenv dependencies
+      - name: Cache Pipenv Packages
         uses: actions/cache@v3
         with:
           path: ~/.cache/pipenv
@@ -31,10 +31,10 @@ jobs:
           restore-keys: |
             pipenv-${{ runner.os }}-
 
-      - name: Install pipenv
+      - name: Setup Install pipenv
         run: pip install pipenv
 
-      - name: Install dependencies
+      - name: Setup Install dependencies
         run: |
           pip --version
           pipenv install && pip install flake8
@@ -47,30 +47,30 @@ jobs:
         working-directory: ./backend
 
   test:
-    name: Backend Run Tests
+    name: Backend Execute Test Cases
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Setup Python
+      - name: Setup install Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.10'
 
-      - name: Install pipenv
+      - name: Setup Install pipenv
         run: |
           pip --version
           pip install pipenv
         working-directory: ./backend
 
-      - name: Install dependencies
+      - name: Setup Install dependencies
         run: |
           pip --version
           pipenv install
         working-directory: ./backend
 
-      - name: Run tests with pipenv
+      - name: Execute Test Cases with pipenv
         run: |
           pipenv --version
           pipenv run test
@@ -79,7 +79,7 @@ jobs:
   build:
     name: Build and Upload Container Image to ECR
     runs-on: ubuntu-latest
-    needs: [lint, test]
+    needs: [ lint, test ]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -119,32 +119,27 @@ jobs:
           REPOSITORY: backend
           IMAGE_TAG: latest
         run: |
-          # Log environment variables
+          # Validate REGISTRY, REPOSITORY, and IMAGE_TAG
+          if [ -z "$REGISTRY" ]; then
+            echo "Error: REGISTRY is empty."
+            exit 1
+          fi
+          if [ -z "$REPOSITORY" ]; then
+            echo "Error: REPOSITORY is empty."
+            exit 1
+          fi
+          if [ -z "$IMAGE_TAG" ]; then
+            echo "Error: IMAGE_TAG is empty."
+            exit 1
+          fi
+
+          echo "Building Docker image with the following details:"
           echo "Registry: $REGISTRY"
           echo "Repository: $REPOSITORY"
           echo "Image Tag: $IMAGE_TAG"
 
-          # Log Dockerfile path
-          echo "Dockerfile path: ./backend/Dockerfile"
-
-          # List current Docker images before build
-          echo "Current Docker images:"
-          docker images
-
           # Build the Docker image
           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./backend/Dockerfile ./backend
-
-          # Check the built Docker image
-          echo "Built Docker image:"
-          docker images | grep $REGISTRY/$REPOSITORY
-
-          # Check if the build was successful or failed
-          if [ $? -eq 0 ]; then
-            echo "Docker image build succeeded."
-          else
-            echo "Docker image build failed."
-            exit 1
-          fi
 
       - name: Push Docker image to ECR
         run: |
