update code git action

diff --git a/.github/workflows/BE-CI.yaml b/.github/workflows/BE-CI.yaml
--- a/.github/workflows/BE-CI.yaml
+++ b/.github/workflows/BE-CI.yaml
@@ -5,18 +5,23 @@ on:
   pull_request:
     branches:
       - main
+      - master
+      - development
     paths:
       - "backend/**"
 
 jobs:
-  lint:
-    name: Backend Linting Jobs
+  setup:
+    name: Setup Python and Dependencies
     runs-on: ubuntu-latest
+    outputs:
+      python-version: ${{ steps.setup-python.outputs.python-version }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
       - name: Setup Python
+        id: setup-python
         uses: actions/setup-python@v5
         with:
           python-version: '3.10'
@@ -34,77 +39,57 @@ jobs:
 
       - name: Install dependencies
         run: |
-          pip --version
-          pipenv install && pip install flake8
+          pipenv install
         working-directory: ./backend
 
-      - name: Run lint with pipenv
-        run: |
-          pipenv --version
-          pipenv run lint
-        working-directory: ./backend
-
-  test:
-    name: Backend Run Tests
+  lint:
+    name: Backend Code Quality Checks
     runs-on: ubuntu-latest
+    needs: setup
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.10'
-
-      - name: Install pipenv
+      - name: Run lint with pipenv
         run: |
-          pip --version
-          pip install pipenv
+          pipenv run lint
         working-directory: ./backend
 
-      - name: Install dependencies
-        run: |
-          pip --version
-          pipenv install
-        working-directory: ./backend
+  test:
+    name: Backend Execute Test Cases
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
 
       - name: Run tests with pipenv
         run: |
-          pipenv --version
           pipenv run test
         working-directory: ./backend
 
   build:
-    name: Build and Push Image to ECR
+    name: Build and Upload Container Image to ECR
     runs-on: ubuntu-latest
     needs: [lint, test]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.10'
-
-      - name: Install pipenv
-        run: |
-          pip --version
-          pip install pipenv && pip install flake8
-        working-directory: ./backend
-
-      - name: Install dependencies
-        run: |
-          pip --version
-          pipenv install
-        working-directory: ./backend
-
-      - name: Configure AWS Credentials
+      - name: Setup AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
+
+      - name: Debug AWS Credentials
+        run: |
+          aws sts get-caller-identity
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: us-east-1
 
       - name: Login to Amazon ECR
         id: login-ecr
@@ -112,20 +97,47 @@ jobs:
         with:
           mask-password: "true"
 
-      - name: Build and Push Docker Image to ECR
-        env:
-          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          REPOSITORY: backend
-          IMAGE_TAG: latest
-        run: |
-          echo "Building Docker image: $REGISTRY/$REPOSITORY:$IMAGE_TAG"
-          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./backend/Dockerfile ./backend
-          docker images
-
-      - name: Cache Docker Image
+      - name: Cache Docker layers
         uses: actions/cache@v3
         with:
           path: ~/.docker
           key: docker-${{ github.sha }}-backend
           restore-keys: |
             docker-${{ github.sha }}-
+
+      - name: Build Docker image
+        env:
+          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          REPOSITORY: backend
+          IMAGE_TAG: latest
+        run: |
+          # Log environment variables
+          echo "Registry: $REGISTRY"
+          echo "Repository: $REPOSITORY"
+          echo "Image Tag: $IMAGE_TAG"
+
+          # Log Dockerfile path
+          echo "Dockerfile path: ./backend/Dockerfile"
+
+          # List current Docker images before build
+          echo "Current Docker images:"
+          docker images
+
+          # Build the Docker image
+          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./backend/Dockerfile ./backend
+
+          # Check the built Docker image
+          echo "Built Docker image:"
+          docker images | grep $REGISTRY/$REPOSITORY
+
+          # Check if the build was successful or failed
+          if [ $? -eq 0 ]; then
+            echo "Docker image build succeeded."
+          else
+            echo "Docker image build failed."
+            exit 1
+          fi
+
+      - name: Push Docker image to ECR
+        run: |
+          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
diff --git a/.github/workflows/FE-CD.yaml b/.github/workflows/FE-CD.yaml
--- a/.github/workflows/FE-CD.yaml
+++ b/.github/workflows/FE-CD.yaml
@@ -5,6 +5,8 @@ on:
   push:
     branches:
       - main
+      - master
+      - development
     paths:
       - 'frontend/**'
 env:
@@ -12,11 +14,8 @@ env:
 
 jobs:
   lint:
-    name: Frontend Linting
+    name: Lint Frontend Code
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./frontend
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -30,45 +29,34 @@ jobs:
             npm-
 
       - name: Install dependencies
-        run: |
-          npm install
+        run: npm install
 
       - name: Run ESLint
-        run: |
-          npm run lint -- --fix
+        run: npm run lint -- --fix
 
   test:
-    name: Frontend Testing
+    name: Run Frontend Unit Tests
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./frontend
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
       - name: Install dependencies
-        run: |
-          npm install
+        run: npm install
 
       - name: Run tests
-        run: |
-          npm test
+        run: npm test
 
   build:
-    name: Build and Push Docker image to Amazon ECR
+    name: Build Docker Image and Push to ECR
     runs-on: ubuntu-latest
     needs: [lint, test]
-    defaults:
-      run:
-        working-directory: ./frontend
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
       - name: Install dependencies
-        run: |
-          npm install
+        run: npm install
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -77,40 +65,39 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
 
+      - name: Debug AWS Credentials
+        run: |
+          aws sts get-caller-identity
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: us-east-1
+
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
         with:
           mask-password: 'true'
 
-      - name: Build And Push Docker Image to ECR
+      - name: Build and Push Docker Image to ECR
         env:
           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           REPOSITORY: frontend
           IMAGE_TAG: latest
         run: |
+          set -e  # Fail on errors
           aws eks update-kubeconfig --name cluster
           export EXTERNALIP=$(kubectl get svc backend -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}{"\n"}{.status.loadBalancer.ingress[0].ip}')
-          echo $EXTERNALIP
+          echo "External IP: $EXTERNALIP"
           echo "Registry: $REGISTRY"
           echo "Repository: $REPOSITORY"
           echo "Image Tag: $IMAGE_TAG"
-          echo "ECR: $REGISTRY/$REPOSITORY:$IMAGE_TAG ."
-          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --build-arg=REACT_APP_MOVIE_API_URL=http://$EXTERNALIP .
-          echo "React API endpoint: http://$EXTERNALIP"
+          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --build-arg REACT_APP_MOVIE_API_URL=http://$EXTERNALIP .
           docker images
           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
 
-      - name: Cache Docker image
-        uses: actions/cache@v3
-        with:
-          path: ~/docker-cache
-          key: docker-${{ github.sha }}-frontend
-          restore-keys: |
-            docker-${{ github.sha }}-
-
   deploy:
-    name: Deploy to Kubernetes
+    name: Deploy Frontend to Kubernetes
     runs-on: ubuntu-latest
     needs: [build]
     steps:
@@ -124,20 +111,23 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
 
+      - name: Debug AWS Credentials
+        run: |
+          aws sts get-caller-identity
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: us-east-1
+
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
         with:
-          mask-password: "true"
+          mask-password: 'true'
 
       - name: Update kubeconfig
         run: |
           aws eks update-kubeconfig --name cluster
-
-      - name: Run init.sh
-        run:  |
-          ./init.sh || true
-        working-directory: ./setup
 
       - name: Set Docker image in Kustomize
         env:
